FROM node:22-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /usr/src/app
ENV NODE_ENV=production
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000
COPY --from=builder /usr/src/app/.output .output
COPY package*.json ./
RUN npm install --omit=dev
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]