services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3100:3000'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
