name: Build and deploy Nuxt 3 Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Update lockfile if needed
        run: npm install

      - name: Verify lockfile
        run: npm ci --dry-run

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt app
        run: npm run build
        env:
          NODE_ENV: production
          # Ajoutez ici vos variables d'environnement si nécessaire
          # API_URL: ${{ secrets.API_URL }}

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp -r .output deploy/
          cp Dockerfile.prod deploy/
          cp docker-compose.prod.yml deploy/
          # Copiez d'autres fichiers nécessaires comme nginx.conf si utilisé

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: portfolio
          path: ./deploy

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: './deploy/*'
          target: '/var/www/html/portfolio'
          strip_components: 1
          overwrite: true

      - name: Restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/html/portfolio
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -f
