name: Build and deploy Nuxt 3 Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Update lockfile if needed
        run: npm install

      - name: Verify lockfile
        run: npm ci --dry-run

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt app
        run: npm run build
        env:
          NODE_ENV: production

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          rsync -av --exclude='deploy' --exclude='.git' --exclude='node_modules' ./ deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio
          path: deploy/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: portfolio
          path: ./deploy

      - name: show user and host info
        run: |
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USERNAME: ${{ secrets.VPS_USERNAME }}"
          echo "VPS_PORT: ${{ secrets.VPS_PORT }}"

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: './deploy/*'
          target: '/var/www/html/portfolio'
          strip_components: 1
          overwrite: true

      - name: Restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/html/portfolio
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -f
